### ISSUE TITLE
engine coffee transaction log

### ISSUE THREAD

**Issue by obeleh** [buttercoin/buttercoin#38]
I noticed the incoming messages first get JSON.parsed @socket.on 'message' and then passed to  engine.receive_message. Wherein it gets JSON.stringified.
- Transaction log is a misleading name. Wouldn't the term disruptionLog be more accurate?
- Shouldn't the disruptionLog be built by a separate process so that the process running the Engine has one less task to do. The disruptor process/service would be tasked to build the disruptorLog, then check the validity of the disruption and then forward the message to the transaction engine. This can then serve as a means to keep the transaction engine discoupled from the internet.
- The engine should then send it's output to the output disruptor. The output disrupt would then build the transaction log. This can be called the transaction log because it actually is the log of performed transactions.

**Comment by enki** [comment]
this isn't a full disruptor design. v1 of buttercoin moves the bottleneck
from disk to memory. next version might move it from memory to cache

operation log might be a better name, since it keeps track of the
operations performed on order book and balances (the two things we are keen
on keeping invariant compliant). or just journal

**Comment by PartTimeLegend** [comment]
Explained by @enki so closed.
